before_script:
  - . ~/.nvm/nvm.sh && nvm use 8

stages:
  - test

test:
  stage: test
  tags:
    - shell
    - mongo
    - elasticsearch
    - redis
  script:
    - npm i
    - npm update
    - bower i
    - grunt --chunk=1 --ci
