image: linagora/node-test-base:8

stages:
  - test
  - deploy_dev

test:
  stage: test
  tags:
    - docker
  services:
    - mongo:3.4
    - elasticsearch:2.4
    - redis:3
    - rabbitmq:3.6
  script:
    - npm i
    - npm update
    - grunt --chunk=1 --ci
deploy_dev:
  stage: deploy_dev
  tags:
    - ticketing.linagora.com
    - deployment
  environment:
    name: dev
    url: http://ticketing.linagora.com
  only:
    - master@linagora/lgs/openpaas/linagora.esn.ticketing
  script:
    - cd /srv/linagora.esn.ticketing
    - git pull origin master
    - npm install --ignore-scripts --production
    - npm update --production
    - npm prune
    - git checkout -- .
    - cd /srv/esn
    - git pull origin master
    - npm install --ignore-scripts --production
    - npm update --production
    - git checkout -- .
    - sudo /etc/init.d/ticketing restart
