image: linagora/node-test-base:8

stages:
  - test
  - deploy_dev

test:
  stage: test
  tags:
    - docker
  services:
    - mongo:3.4
    - elasticsearch:2.4
    - redis:3
    - rabbitmq:3.6
  script:
    - npm i
    - npm update
    - grunt --chunk=1 --ci
deploy_dev:
  stage: deploy_dev
  except:
    - triggers
  tags:
    - dev.open-paas.org
    - deployment
  environment:
    name: dev
    url: https://dev.open-paas.org
  only:
    - master@linagora/lps/studio/ticketing08000linux.backend
  script:
    - cd /srv/${CI_PROJECT_NAME}
    - git fetch --all
    - git checkout ${CI_COMMIT_SHA}
    - npm install --ignore-scripts --production
    - npm update --production
    - npm prune
    - git checkout -- .
    - sudo /etc/init.d/rse.dev restart
